name: Publish site to gh-pages
on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Checkout main
          uses: actions/checkout@v4.2.2
        - name: Build 
          uses: shalzz/zola-deploy-action@v0.20.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BUILD_ONLY: true
        - name: Compile cards
          uses: xu-cheng/latex-action@v3
          with:
            root_file: |
              main.tex
              sepcards.tex
            working_directory: tex
            latexmk_use_xelatex: true
            texlive_version: 2024
        - name: Move file
          run: sudo cp tex/main.pdf  $GITHUB_WORKSPACE/public/fevronia-cards.pdf
        - name: Move file
          run: sudo cp tex/sepcards.pdf  $GITHUB_WORKSPACE/public/fevronia-separate-cards.pdf
        - name: Upload artefact
          uses: actions/upload-pages-artifact@v3.0.1
          with:
            path: public/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build_and_deploy

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
